{
 "title": "My own",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ram Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\", mode=\"idle\"}[1m]))",
     "legendFormat": "System idle"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\", mode=\"system\"}[1m]))",
     "legendFormat": "Busy system"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", job=\"node\", mode=\"user\"}[1m]))",
     "legendFormat": "Busy User"
    }
   ]
  }
 ]
}